name: ShapelessPortal
main: com.lith.shapelessportal.Plugin

version: 0.0.2
api-version: 1.20

description: A MineCraft plugin to allow players to create any shape for a Nether Portal. Can also use crying obsidian.
author: Lith
website: https://github.com/ImLith/MC-ShapelessPortals

depend: [LithCore]
softdepend: []

commands:
  spReload:
    description: Reload configs
    usage: /<command>
    permission: shaplessportals.reload

permissions:
  shaplessportals.reload:
    description: Reload configs
    default: op
